version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --continue --stacktrace --no-daemon --profile -Dscan

test_script:
  - gradlew.bat check build --continue --stacktrace --no-daemon --profile -Dscan

on_finish:
  - 7z a reports.zip .\build\reports && appveyor PushArtifact reports.zip
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $wc = New-Object 'System.Net.WebClient'
      ForEach ($file in Get-ChildItem '.\build\test-results\test\*.xml') {
        Write-Host "Uploading test result: $file"
        $wc.UploadFile($url, $file)
      }

cache:
  - C:\Users\appveyor\.gradle

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
